version: '3.8'
services:
  db:
    build: ./db
    container_name: investment_db
    networks:
      - investment-network
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

networks:
  investment-network:
    name: investment-network
    driver: bridge